### PR TITLE
 add RSGraviton_hh_htatahbb

### PR DESCRIPTION
**Pull request by cgalloni**

### CODE REVIEW

**Comment by cgalloni** [comment]
add RSGraviton_hh_htatahbb  config files

**Comment by syuvivida** [comment]
Hi Camilla,
  Can you check why the output python files have HTML format?

Eiko

**Comment by cgalloni** [comment]
Hello Eiko,
I think I followed the instructions and did the steps 2,3,4,5 in a 
directory prova_dir_RSGraviton_hh_htatahbb  that i paste in my public 
area in the folder 4Eiko, if you want to have a look.
At the end of those steps the RSGraviton_hh_htatahbb folder is produced.

Could you check if some of the files are wrong?

Thank you very much.

Camilla

Il 8/11/15 4:38 PM, syuvivida ha scritto:

**Comment by syuvivida** [comment]
Hi Camilla,
  You need to download template_cff.py again. My former version of instruction gave 
an incorrect address. The instruction updated today has fixed this.

curl https://raw.githubusercontent.com/syuvivida/DibosonBSMSignal_13TeV/master/gridpack_folder/mc_request/template_cff.py -o template_cff.py

**Comment by cgalloni** [comment]
the new python file seem to have at least the proper format! :) 
Thanks a lot for your help

**Pull request closed without merging**
